[package]
name = "klauncher"
version = "0.1.0"
authors = ["Wyatt Jacob Herkamp <wherkamp@kingtux.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.133", features = ["derive"] }
serde_yaml = "0.8.23"
discord-rpc-client = "0.3.0"
reqwest = { version = "0.11.9", features = ["json"] }
tokio = { version = "1.15.0", features = ["full"] }
futures = "0.3.19"
jenkins_api = "0.8.0"
indicatif = "0.16.2"
zip = "0.5.13"
thiserror = "1.0.30"
nitro_log = { git = "https://github.com/wherkamp/nitro_log", features = ["time", "colors"] }
log = "0.4.14"
serde_json = "1.0.71"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser", "tlhelp32", "processthreadsapi", "synchapi", "impl-default"] }