name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      env:
        DISCORD_KEY: ${{ secrets.DISCORD_KEY }}
    - uses: actions/upload-artifact@v2
      with:
       name: KLauncher
       path: target\debug\klauncher.exe
